import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import vm from 'node:vm';
import { describe, expect, it } from 'vitest';

const source = readFileSync(resolve(import.meta.dirname, '../../extension/content-youtube.js'), 'utf8');
function loadPlayer({ items = [], task = null, token = 'token', nativeLanguage = 'zh-Hans', sourceLanguage = 'en', failRead = false, pauseRead, pausePost, onPost } = {}) {
  const requests = [];
  const events = [];
  const status = { textContent: '', classList: { add() {}, remove() {}, toggle() {} } };
  const sandbox = {
    URLSearchParams, URL, encodeURIComponent, console,
    location: { hostname: 'www.youtube.com', pathname: '/watch', search: '?v=video-1' },
    document: { readyState: 'loading', addEventListener() {}, querySelector: () => status, getElementById: () => null },
    CustomEvent: class { constructor(type, init = {}) { this.type = type; this.detail = init.detail; } },
    window: { dispatchEvent: (event) => events.push(event) },
    chrome: {
      storage: { local: { get: (_keys, cb) => cb({ auth_token: token, nativeLanguage }), set() {}, remove() {} } },
      runtime: {
        onMessage: { addListener() {} },
        getURL: (path) => path,
        sendMessage: async (message) => {
          requests.push(message);
          if (message.method === 'GET') {
            if (pauseRead) await pauseRead;
            if (failRead) return { error: true, status: 503, message: 'Unavailable' };
            const target = new URL(message.path, 'https://lingread.app').searchParams.get('targetLanguage');
            return { data: { videoId: 'video-1', targetLanguage: target, items: typeof items === 'function' ? items(target) : items, task, terminology: [] } };
          }
          if (message.method === 'POST') {
            onPost?.();
            if (pausePost) await pausePost;
            if (message.path === '/api/youtube/metadata/translate') {
              return { data: { title: '中文视频标题', description: '中文简介' } };
            }
            return { data: { taskId: 'task-1', status: 'idle' } };
          }
          return { ok: true };
        },
      },
    },
    crypto: { randomUUID: () => 'relay-1' },
    setInterval: () => 1, clearInterval() {},
  };
  // Run the real script without booting YouTube DOM discovery.
  const exposed = source.replace(/\}\)\(\);\s*$/, `
    currentContext = { videoId: 'video-1', title: 'Video', subtitles: {
      segments: [{ start: 0, end: 2, text: 'Hello' }], language: '${sourceLanguage}', isAutoGenerated: false
    } };
    refreshModeRow = () => {};
    broadcastContext = (context) => window.dispatchEvent(new CustomEvent('yst:yt:context-ready', { detail: context }));
    globalThis.player = {
      select: setSubtitleMode,
      resume: resumeSubtitleFetchAfterLogin,
      title: ensureVideoTitleTranslation,
      changeLanguage: changeNativeLanguage,
      useCachedContext(pauseBuild) {
        const loadedContext = currentContext;
        currentContext = { videoId: 'video-1', subtitles: {
          fromCache: true, segments: [{ start: 0, end: 1, text: 'Partial' }]
        } };
        buildContext = async () => { if (pauseBuild) await pauseBuild; return loadedContext; };
      },
      clearContext() {
        const loadedContext = currentContext;
        currentContext = null;
        buildContext = async () => loadedContext;
      },
    };
  })();`);
  vm.runInNewContext(readFileSync('extension/languages.js', 'utf8'), sandbox);
  sandbox.window.YST_LANGUAGES = sandbox.YST_LANGUAGES;
  vm.runInNewContext(exposed, sandbox);
  return { ...sandbox.player, requests, events, status, login: () => { token = 'new-token'; }, navigate: () => { sandbox.location.search = '?v=video-2'; } };
}
const translated = [{ start: 0, end: 2, text: 'Hello', translation: '你好' }];
const dashboards = (p) => p.requests.filter((r) => r.action === 'nav:openHistory');
const posts = (p) => p.requests.filter((r) => r.method === 'POST');

describe('YouTube subtitle mode selection', () => {
  it('uses the selected native language for cache reads, task creation and the dashboard', async () => {
    const p = loadPlayer({ nativeLanguage: 'ja' });
    await p.select('bilingual');
    expect(p.requests.find(r => r.method === 'GET').path).toContain('targetLanguage=ja');
    expect(JSON.parse(posts(p)[0].body)).toMatchObject({ sourceLanguage: 'en', targetLanguage: 'ja' });
    expect(dashboards(p)[0].path).toContain('targetLanguage=ja');
  });
  it('shows original captions without requesting translation when source and native languages match', async () => {
    const p = loadPlayer({ nativeLanguage: 'ja', sourceLanguage: 'ja', token: null });
    await p.select('bilingual');
    expect(p.events.some(e => e.type === 'yst:yt:activate-subtitles')).toBe(true);
    expect(p.requests).toHaveLength(0);
  });
  it('loads original captions before deciding whether a same-language video needs login', async () => {
    const p = loadPlayer({ nativeLanguage: 'ja', sourceLanguage: 'ja', token: null });
    p.clearContext();
    await p.select('target');
    expect(p.events.some(e => e.type === 'yst:yt:activate-subtitles')).toBe(true);
    expect(p.requests).toHaveLength(0);
  });
  it('regenerates a Chinese source cache incorrectly saved for an English video', async () => {
    const p = loadPlayer({ items: [{ start: 0, end: 2, text: '这一段字幕原文错误地变成了中文', translation: '这一段字幕仍然是中文' }] });
    await p.select('bilingual');
    expect(posts(p)).toHaveLength(1);
    expect(JSON.parse(posts(p)[0].body)).toMatchObject({ force: true, sourceLanguage: 'en' });
  });
  it('clears the old language before loading a new native-language cache', async () => {
    const p = loadPlayer({ items: target => [{ start: 0, end: 2, text: 'Hello', translation: target === 'ja' ? 'こんにちは' : '你好' }] });
    await p.select('bilingual');
    await p.changeLanguage('ja');
    const cleared = p.events.findIndex(e => e.type === 'yst:yt:context-cleared');
    expect(cleared).toBeGreaterThan(0);
    const newData = p.events.slice(cleared).find(e => e.type === 'yst:yt:subtitles-data');
    expect(newData.detail).toMatchObject({ targetLanguage: 'ja', items: [{ translation: 'こんにちは' }] });
    expect(posts(p)).toHaveLength(0);
  });
  it.each(['ja', 'en'])('restores original captions from a cached context when switching to uncached %s', async target => {
    const p = loadPlayer({ items: language => language === 'zh-Hans' ? translated : [] });
    await p.select('bilingual');
    p.useCachedContext();
    await p.changeLanguage(target);
    const cleared = p.events.findLastIndex(e => e.type === 'yst:yt:context-cleared');
    const subsequent = p.events.slice(cleared + 1);
    expect(subsequent.find(e => e.type === 'yst:yt:context-ready')?.detail.subtitles).toMatchObject({
      language: 'en', segments: [{ text: 'Hello', end: 2 }],
    });
    expect(subsequent.some(e => e.type === 'yst:yt:activate-subtitles')).toBe(true);
    expect(posts(p)).toHaveLength(0);
    if (target === 'en') expect(p.requests.filter(r => r.method === 'GET')).toHaveLength(1);
  });
  it('keeps captions active through rapid native-language changes while rebuilding the source', async () => {
    let release;
    const pauseBuild = new Promise(resolve => { release = resolve; });
    const p = loadPlayer({ items: language => language === 'zh-Hans' ? translated : [] });
    await p.select('bilingual');
    p.useCachedContext(pauseBuild);
    const first = p.changeLanguage('ja');
    const second = p.changeLanguage('en');
    release();
    await Promise.all([first, second]);
    const cleared = p.events.findLastIndex(e => e.type === 'yst:yt:context-cleared');
    const subsequent = p.events.slice(cleared + 1);
    expect(subsequent.filter(e => e.type === 'yst:yt:context-ready')).toHaveLength(1);
    expect(subsequent.some(e => e.type === 'yst:yt:activate-subtitles')).toBe(true);
    expect(p.requests.filter(r => r.method === 'GET')).toHaveLength(1);
  });
  it.each(['bilingual', 'target'])('loads translations when selecting %s, including the default mode', async (mode) => {
    const p = loadPlayer({ items: translated });
    await p.select(mode);
    expect(p.events.find((e) => e.type === 'yst:yt:subtitles-data')?.detail.items).toEqual(translated);
    expect(p.events.find((e) => e.type === 'yst:yt:activate-subtitles')?.detail.videoId).toBe('video-1');
    expect(posts(p)).toHaveLength(0);
    expect(dashboards(p)).toHaveLength(0);
  });
  it('saves an untranslated video and opens translation without forcing regeneration', async () => {
    const p = loadPlayer();
    await p.select('bilingual');
    expect(posts(p)).toHaveLength(1);
    expect(JSON.parse(posts(p)[0].body)).toMatchObject({ videoId: 'video-1', force: false });
    expect(dashboards(p).map((r) => r.path)).toEqual(['/dashboard?tab=video&videoId=video-1&targetLanguage=zh-Hans']);
  });
  it.each(['idle', 'pending', 'running'])('opens an existing %s task without creating another', async (status) => {
    const p = loadPlayer({ task: { taskId: 'existing', status, totalSegments: 2, completedSegments: 0 } });
    await p.select('target');
    expect(posts(p)).toHaveLength(0);
    expect(dashboards(p)).toHaveLength(1);
  });
  it('retries a failed task even when its phase cache contains subtitle items', async () => {
    const p = loadPlayer({
      items: translated,
      task: { taskId: 'failed-task', status: 'failed', totalSegments: 2, completedSegments: 2 },
    });
    await p.select('target');
    expect(posts(p)).toHaveLength(1);
    expect(JSON.parse(posts(p)[0].body)).toMatchObject({ videoId: 'video-1', force: false });
    expect(dashboards(p)).toHaveLength(1);
  });
  it.each([null, { taskId: 'old-task', status: 'canceled' }])('retries partial caches with the complete original track when task is %j', async task => {
    const p = loadPlayer({ items: [{ start: 0, end: 1, text: 'Partial', translation: '部分' }], task });
    p.useCachedContext();
    await p.select('target');
    expect(posts(p)).toHaveLength(1);
    expect(JSON.parse(posts(p)[0].body)).toMatchObject({
      force: false, subtitles: [{ start: 0, end: 2, text: 'Hello' }],
    });
    expect(dashboards(p)).toHaveLength(1);
  });
  it.each(['source', 'off'])('does not fetch or open translation for %s', async (mode) => {
    const p = loadPlayer();
    await p.select(mode);
    expect(p.requests).toHaveLength(0);
  });
  it('does not mistake a failed check for missing translations', async () => {
    const p = loadPlayer({ failRead: true });
    await p.select('target');
    expect(posts(p)).toHaveLength(0);
    expect(dashboards(p)).toHaveLength(0);
    expect(p.status.textContent).toContain('重试');
  });
  it('starts login when translation is missing', async () => {
    const p = loadPlayer({ token: null });
    await p.select('target');
    expect(p.requests.filter((r) => r.action === 'auth:startRelay')).toHaveLength(1);
    expect(posts(p)).toHaveLength(0);
  });
  it('loads shared translations without login', async () => {
    const p = loadPlayer({ token: null, items: translated });
    await p.select('target');
    expect(p.events.some((e) => e.type === 'yst:yt:activate-subtitles')).toBe(true);
    expect(p.requests.filter((r) => r.action === 'auth:startRelay')).toHaveLength(0);
  });
  it('coalesces rapid translated-mode clicks into one navigation', async () => {
    let release;
    const pauseRead = new Promise((resolve) => { release = resolve; });
    const p = loadPlayer({ pauseRead });
    const first = p.select('bilingual');
    const second = p.select('target');
    release();
    await Promise.all([first, second]);
    expect(posts(p)).toHaveLength(1);
    expect(dashboards(p)).toHaveLength(1);
  });
  it.each(['navigate', 'off'])('ignores a pending check after %s', async (action) => {
    let release;
    const pauseRead = new Promise((resolve) => { release = resolve; });
    const p = loadPlayer({ pauseRead });
    const pending = p.select('target');
    if (action === 'navigate') p.navigate();
    else await p.select(action);
    release();
    await pending;
    expect(posts(p)).toHaveLength(0);
    expect(dashboards(p)).toHaveLength(0);
  });
  it('continues the selected video after login', async () => {
    const p = loadPlayer({ token: null });
    await p.select('target');
    p.login();
    await p.resume();
    expect(posts(p)).toHaveLength(1);
    expect(dashboards(p)).toHaveLength(1);
  });

  it('fetches and caches the translated video title for the popup', async () => {
    const p = loadPlayer();
    const context = { videoId: 'video-1', title: 'Video', description: '' };
    await p.title(context);
    await p.title(context);
    const titleRequests = p.requests.filter((r) => r.path === '/api/youtube/metadata/translate');
    expect(titleRequests).toHaveLength(1);
    expect(JSON.parse(titleRequests[0].body)).toMatchObject({
      videoId: 'video-1',
      title: 'Video',
      targetLanguage: 'zh-Hans',
    });
  });
  it.each(['navigate', 'off'])('does not resume login after %s', async (action) => {
    const p = loadPlayer({ token: null });
    await p.select('target');
    if (action === 'navigate') p.navigate();
    else await p.select(action);
    p.login();
    await p.resume();
    expect(posts(p)).toHaveLength(0);
    expect(dashboards(p)).toHaveLength(0);
  });
  it.each(['navigate', 'off'])('does not open a page when %s happens during task creation', async (action) => {
    let release;
    let onPost;
    const pausePost = new Promise((resolve) => { release = resolve; });
    const posted = new Promise((resolve) => { onPost = resolve; });
    const p = loadPlayer({ pausePost, onPost });
    const pending = p.select('target');
    await posted;
    if (action === 'navigate') p.navigate();
    else await p.select(action);
    release();
    await pending;
    expect(posts(p)).toHaveLength(1);
    expect(dashboards(p)).toHaveLength(0);
  });

  it('activates subtitles after loading missing context for a keyboard selection', async () => {
    const p = loadPlayer();
    p.clearContext();
    await p.select('target');
    const contextIndex = p.events.findIndex((e) => e.type === 'yst:yt:context-ready');
    const activationIndex = p.events.findIndex((e) => e.type === 'yst:yt:activate-subtitles');
    expect(contextIndex).toBeGreaterThanOrEqual(0);
    expect(activationIndex).toBeGreaterThan(contextIndex);
    expect(p.events[activationIndex].detail.videoId).toBe('video-1');
    expect(dashboards(p)).toHaveLength(1);
  });

});
